Readme edit
pwndoc-ng/pwndoc-ng pull request #144
Opened 2023-03-31 17:00 UTC by diggidong

As discussed with @Zeecka I added Quick Setup information to the README.md.

2023-03-31 17:54 UTC, Zeecka requested changes

2023-03-31 17:54 UTC, Zeecka commented on README.md
There is a bit too much information for the Quick setup. Maybe you can provide 2-3 commands including git pull & docker compose up, and a link related to full documentation ?

2023-04-01 13:30 UTC, diggidong commented
I have shortened the installation description in the README.md.

2023-04-01 14:44 UTC, Zeecka commented
Sorry, but it doesn't fit our expectation :/.

2023-04-01 14:44 UTC, closed without merging